----
# **<span style="color:DarkSlateBlue">PROYECTO BOOKING_REVIEWS</span>**
# **<span style="color:DarkSlateBlue">Limpieza de datos</span>**
----

---
---
## <span style="color:gray">**1. Importación de librerías**</span> 📂

In [ ]:
# Tratamiento de datos
import numpy as np
import pandas as pd 
from IPython.display import display

# Visualización de datos
import seaborn as sns
import matplotlib.pyplot as plt

# Configuración de ruta
import sys
sys.path.append('../')

# Importación de funciones personalizadas
from src.soporte2_limpieza import *

---
---
## <span style="color:gray">**2. Carga de datos**</span> 📥

In [ ]:
booking_raw = pd.read_csv("../data/raw/hotel_booking.csv")

reviews_raw = pd.read_csv("../data/raw/hotel_reviews.csv")

In [ ]:
# Configuración para mostrar todas las columnas
pd.set_option('display.max_columns', None)

---
---

----
# <span style="color:DarkSlateBlue">**Desarrollo del proyecto - 2**</span>
----

---
---
## <span style="color:gray">**Limpieza de datos**</span> 🧹

Antes de continuar con el análisis exploratorio de datos (EDA), creamos copias de los DataFrames originales.
Esto nos permite manipular, limpiar o transformar los datos sin afectar los originales, asegurando que siempre podamos recuperar la información original si es necesario.

In [ ]:
booking_limpio = booking_raw.copy()
reviews_limpio = reviews_raw.copy()

---
## `booking_limpio`

### <span style="color:darkgray">**1. Estandarización de nombres de columnas**</span>

La única columna a la cual tenemos que estandarizar el nombre es a `phone-number`.

In [ ]:
booking_limpio.rename(columns={'phone-number': 'phone_number'}, inplace=True)

### <span style="color:darkgray">**2. Eliminación de columnas irrelevantes**</span>

- `arrival_date_week_number` 

- `agent`y `company` - representan los ID de las agencias y compañías, por lo tanto no es un dato relevante para nuestro análisis

- `name`, `email`, `phone_number`, `credit_card`

**Eliminamos las columnas anteriores**

In [ ]:
# Llamamos a la función para eliminar columnas de un DataFrame guardada en el archivo de soporte
booking_limpio = eliminar_columns(
    booking_limpio,
    ["arrival_date_week_number", "agent", "company" ,"name", "email", "phone_number", "credit_card"]
)

### <span style="color:darkgray">**3. Limpieza de strings**</span>

- **Comprobamos los datos únicos de las variables categóricas y hacemos la limpieza de algunos de los datos.**

In [ ]:
col_cat = booking_limpio.select_dtypes(include=['category', 'str']).columns
datos_unicos(booking_limpio, col_cat)

Los datos únicos de la varible hotel son:

 <StringArray>
['Resort Hotel', 'City Hotel']
Length: 2, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible arrival_date_month son:

 <StringArray>
[     'July',    'August', 'September',   'October',  'November',  'December',
   'January',  'February',     'March',     'April',       'May',      'June']
Length: 12, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible meal son:

 <StringArray>
['BB', 'FB', 'HB', 'SC', 'Undefined']
Length: 5, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible country son:

 <StringArray>
['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA',   nan, 'ROU', 'NOR', 'OMN',
 ...
 'ATA', 'GTM', 'ASM', 'MRT', 'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO']
Length: 178, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible market_segment son:

 <StringArray>
[       'Direct',     'Corporate',     'Online TA', 'Offline TA/TO',
 'Complementary',        'Groups',     'Undefined',      'Aviation']
Length: 8, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible distribution_channel son:

 <StringArray>
['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS']
Length: 5, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible reserved_room_type son:

 <StringArray>
['C', 'A', 'D', 'E', 'G', 'F', 'H', 'L', 'P', 'B']
Length: 10, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible assigned_room_type son:

 <StringArray>
['C', 'A', 'D', 'E', 'G', 'F', 'I', 'B', 'H', 'P', 'L', 'K']
Length: 12, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible deposit_type son:

 <StringArray>
['No Deposit', 'Refundable', 'Non Refund']
Length: 3, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible customer_type son:

 <StringArray>
['Transient', 'Contract', 'Transient-Party', 'Group']
Length: 4, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible reservation_status son:

 <StringArray>
['Check-Out', 'Canceled', 'No-Show']
Length: 3, dtype: str


-----------------------------------------------------------------


Los datos únicos de la varible reservation_status_date son:

 <StringArray>
['2015-07-01', '2015-07-02', '2015-07-03', '2015-05-06', '2015-04-22',
 '2015-06-23', '2015-07-05', '2015-07-06', '2015-07-07', '2015-07-08',
 ...
 '2015-03-13', '2015-05-05', '2015-03-29', '2015-06-10', '2015-04-27',
 '2014-10-17', '2015-01-20', '2015-02-17', '2015-03-10', '2015-03-23']
Length: 926, dtype: str


-----------------------------------------------------------------

- Todas las variables presentan mayúsculas y minúsculas, lo estandarizamos todo a minúsculas.
- Las variables `hotel`, `deposit_type` y `market_segment` tienen algunos datos con espacio entre medias, lo cambiamos por "_".
- `market_segment` y `distribution_channel` tienen el caracter "/", el cual sustituimos por "_".
- `customer_type`y `reservation_status` tienen comor separador de palabras "-", lo cambiamos por "_".

In [ ]:
# Llamamos a la función que transforma datos a minúscula guardada en el archivo de sorporte
minus(booking_limpio, col_cat)

# Llamamos a la función reemplazar guardada en el archivo de soporte 
reemplazar(booking_limpio, ["hotel", "deposit_type", "market_segment"], " ", "_")
reemplazar(booking_limpio, ["market_segment", "distribution_channel"], "/", "_")
reemplazar(booking_limpio, ["customer_type", "reservation_status"], "-", "_")

- **Cambiamos la abreviatura de los países por el nombre completo del país.**

1. Creamos un diccionario con todos los países.

In [ ]:
country_dict = {
    'prt': 'Portugal', 'gbr': 'United Kingdom', 'usa': 'United States',
    'esp': 'Spain', 'irl': 'Ireland', 'fra': 'France', 'rou': 'Romania',
    'nor': 'Norway', 'omn': 'Oman', 'arg': 'Argentina', 'pol': 'Poland',
    'deu': 'Germany', 'bel': 'Belgium', 'che': 'Switzerland',
    'cn': 'China', 'chn': 'China', 'grc': 'Greece', 'ita': 'Italy',
    'nld': 'Netherlands', 'dnk': 'Denmark', 'rus': 'Russia',
    'swe': 'Sweden', 'aus': 'Australia', 'est': 'Estonia',
    'cze': 'Czech Republic', 'bra': 'Brazil', 'fin': 'Finland',
    'lux': 'Luxembourg', 'svn': 'Slovenia', 'alb': 'Albania',
    'ind': 'India', 'mex': 'Mexico', 'mar': 'Morocco',
    'ukr': 'Ukraine', 'aut': 'Austria', 'blr': 'Belarus',
    'ltu': 'Lithuania', 'tur': 'Turkey', 'zaf': 'South Africa',
    'isr': 'Israel', 'hun': 'Hungary', 'are': 'United Arab Emirates',
    'tun': 'Tunisia', 'hrv': 'Croatia', 'hkg': 'Hong Kong',
    'irn': 'Iran', 'col': 'Colombia', 'svk': 'Slovakia',
    'nzl': 'New Zealand', 'tha': 'Thailand', 'dom': 'Dominican Republic',
    'mys': 'Malaysia', 'jpn': 'Japan', 'lka': 'Sri Lanka',
    'bgr': 'Bulgaria', 'sgp': 'Singapore', 'sau': 'Saudi Arabia',
    'vnm': 'Vietnam', 'qat': 'Qatar', 'egy': 'Egypt',
    'per': 'Peru', 'mlt': 'Malta', 'ecu': 'Ecuador',
    'isl': 'Iceland', 'uzb': 'Uzbekistan', 'npl': 'Nepal',
    'twn': 'Taiwan', 'eth': 'Ethiopia', 'irq': 'Iraq',
    'hnd': 'Honduras', 'rwa': 'Rwanda', 'khm': 'Cambodia',
    'bgd': 'Bangladesh', 'tza': 'Tanzania', 'gha': 'Ghana',
    'ken': 'Kenya', 'pan': 'Panama', 'bol': 'Bolivia',
    'pry': 'Paraguay', 'slv': 'El Salvador', 'guy': 'Guyana',
    'gtm': 'Guatemala', 'sdn': 'Sudan', 'lao': 'Laos',
    'moz': 'Mozambique', 'bwa': 'Botswana', 'smr': 'San Marino',
    'lva': 'Latvia', 'pri': 'Puerto Rico', 'srb': 'Serbia',
    'chl': 'Chile', 'ago': 'Angola', 'cym': 'Cayman Islands',
    'zmb': 'Zambia', 'cpv': 'Cape Verde', 'zwe': 'Zimbabwe',
    'dza': 'Algeria', 'kor': 'South Korea', 'cri': 'Costa Rica',
    'jam': 'Jamaica', 'geo': 'Georgia', 'and': 'Andorra',
    'gib': 'Gibraltar', 'ury': 'Uruguay', 'jey': 'Jersey',
    'caf': 'Central African Republic', 'cyp': 'Cyprus',
    'ggy': 'Guernsey', 'kwt': 'Kuwait', 'nga': 'Nigeria',
    'mdv': 'Maldives', 'ven': 'Venezuela', 'fji': 'Fiji',
    'kaz': 'Kazakhstan', 'pak': 'Pakistan', 'idn': 'Indonesia',
    'lbn': 'Lebanon', 'phl': 'Philippines', 'sen': 'Senegal',
    'syc': 'Seychelles', 'aze': 'Azerbaijan', 'bhr': 'Bahrain',
    'mkd': 'North Macedonia', 'arm': 'Armenia', 'cub': 'Cuba',
    'cmr': 'Cameroon', 'bih': 'Bosnia and Herzegovina',
    'mus': 'Mauritius', 'com': 'Comoros', 'sur': 'Suriname',
    'uga': 'Uganda', 'civ': "Cote d Ivoire", 'jor': 'Jordan',
    'syr': 'Syria', 'bdi': 'Burundi', 'plw': 'Palau',
    'mwi': 'Malawi', 'mdg': 'Madagascar', 'bhs': 'Bahamas',
    'mac': 'Macau', 'tgo': 'Togo', 'dji': 'Djibouti',
    'stp': 'Sao Tome and Principe', 'kna': 'Saint Kitts and Nevis',
    'mco': 'Monaco', 'imn': 'Isle of Man', 'tjk': 'Tajikistan',
    'nic': 'Nicaragua', 'ben': 'Benin', 'vgb': 'British Virgin Islands', 
    'gab': 'Gabon', 'tmp': 'East Timor', 'glp': 'Guadeloupe', 
    'lie': 'Liechtenstein', 'gnb': 'Guinea Bissau', 'mne': 'Montenegro',
    'umi': 'United States Minor Outlying Islands', 'myt': 'Mayotte', 
    'fro': 'Faroe Islands', 'mmr': 'Myanmar', 'bfa': 'Burkina Faso', 
    'lby': 'Libya', 'mli': 'Mali', 'nam': 'Namibia', 'brb': 'Barbados', 
    'abw': 'Aruba', 'aia': 'Anguilla', 'dma': 'Dominica', 'pyf': 'French Polynesia',
    'lca': 'Saint Lucia', 'ata': 'Antarctica', 'asm': 'American Samoa', 
    'mrt': 'Mauritania', 'ncl': 'New Caledonia', 'kir': 'Kiribati',
    'atf': 'French Southern Territories', 'sle': 'Sierra Leone'
}

2. Lo aplicamos al DataFrame

In [ ]:
booking_limpio['country'] = booking_limpio['country'].map(country_dict)

3. Estandarizamos la columna

In [ ]:
booking_limpio['country'] = booking_limpio['country'].str.lower().str.strip().str.replace(" ", "_")

### <span style="color:darkgray">**4. Corrección de tipos de datos**</span>

- **Cambiamos las variables `is_canceled` y `is_repeated_guest` a variables categóricas:** 

   - 1 = 'si'
   - 0 = 'no'

In [ ]:
columnas = ["is_canceled", "is_repeated_guest"]

for columna in columnas:
    booking_limpio[columna] = booking_limpio[columna].replace({1:'si', 0:'no'})

- **Variable `children`**

Para convertir esta variable a números enteros, primero hay que pasar de string a float, hacer un redondeo al entero más cercano y finalmente se cambia a int:

In [ ]:
booking_limpio['children'] = booking_limpio['children'].astype('Int64')

- **Variable `reservation_status_date`**

In [ ]:
booking_limpio["reservation_status_date"] = (
    pd.to_datetime(booking_limpio["reservation_status_date"], 
                   format="%Y-%M-%d", 
                   errors="coerce")
                   )

Una vez convertida la variable a formato fecha, se crearán dos nuevas variables: una que contenga el año y otra el mes, con el objetivo de obtener información temporal más relevante para el análisis.

In [ ]:
booking_limpio['reservation_status_year'] = booking_limpio['reservation_status_date'].dt.year

In [ ]:
booking_limpio['reservation_status_month'] = booking_limpio['reservation_status_date'].dt.month_name()

- Comprobamos que se han creado correctamente:

In [ ]:
booking_limpio.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_day_of_month       119390 non-null  int64
 6   stays_in_weekend_nights         119390 non-null  int64
 7   stays_in_week_nights            119390 non-null  int64
 8   adults                          119390 non-null  int64
 9   children                        119386 non-null  Int64
 10  babies                          119390 non-null  int64
 11  meal                            119390 non-null  str
 12  country                         118902 non-null  str
 13  market_segment                  119390 non-null  str
 14  distribution_channel            119390 non-null  str
 15  is_repeated_guest               119390 non-null  object
 16  previous_cancellations          119390 non-null  int64
 17  previous_bookings_not_canceled  119390 non-null  int64
 18  reserved_room_type              119390 non-null  str
 19  assigned_room_type              119390 non-null  str
 20  booking_changes                 119390 non-null  int64
 21  deposit_type                    119390 non-null  str
 22  days_in_waiting_list            119390 non-null  int64
 23  customer_type                   119390 non-null  str
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status              119390 non-null  str
 28  reservation_status_date         119390 non-null  datetime64[us]
 29  reservation_status_year         119390 non-null  int32
 30  reservation_status_month        119390 non-null  str
dtypes: Int64(1), datetime64[us](1), float64(1), int32(1), int64(13), object(2), str(12)
memory usage: 27.9+ MB

### <span style="color:darkgray">**5. Tratamiento de valores nulos**</span>

Durante la exploración inicial del Dataset, identificamos columnas con valores nulos; a continuación, evaluaremos cómo tratarlos individualmente.

Antes de tratar los nulos generamos un DataFrame que contenga solo las columnas que tienen nulos:

In [ ]:
df_nulos = booking_limpio.loc[:, booking_limpio.isnull().sum() > 0]
df_nulos.columns

Index(['children', 'country'], dtype='str')

Recordamos el porcentaje de nulos de cada columna:

In [ ]:
(df_nulos.isnull().sum() / (df_nulos.shape[0])*100).round(3)

children    0.003
country     0.409
dtype: float64

- Variable `children`

Lo imputamos con la moda.

In [ ]:
booking_limpio["children"] = booking_limpio["children"].fillna(booking_limpio["children"].mode()[0])


- Variable `country`

Sustituímos los valores nulos por 'unknown'.

In [ ]:
booking_limpio["country"] = booking_limpio["country"].fillna('unknown')

Comprobamos que se han eliminado todos los nulos correctemente:

In [ ]:
booking_limpio.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
reservation_status_year           0
reservation_status_month          0
dtype: int64

---
## `reviews_limpio`

### <span style="color:darkgray">**1. Estandarización de nombres de columnas**</span>

- Estandarización de nombres de las columnas

In [ ]:
estandar_columns(reviews_limpio)

### <span style="color:darkgray">**2. Transformación de los datos de la variable `id` a minúsculas**</span>

---
---
## <span style="color:gray">**Validación final de los datasets**</span> ✅

- **Comprobamos que la limpieza de ambos dataset se ha realizado correctamente**


### **`booking_limpio`**

In [ ]:
# Llamamos a la función analisis_rapido guardada en el archivo de soporte
analisis_rapido(booking_limpio)

Las 3 primeras filas del Dataframe son:

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,reservation_status_year,reservation_status_month
0,resort_hotel,no,342,2015,july,1,0,0,2,0,0,bb,portugal,direct,direct,no,0,0,c,c,3,no_deposit,0,transient,0.0,0,0,check_out,2015-01-01 00:07:00,2015,January
1,resort_hotel,no,737,2015,july,1,0,0,2,0,0,bb,portugal,direct,direct,no,0,0,c,c,4,no_deposit,0,transient,0.0,0,0,check_out,2015-01-01 00:07:00,2015,January
2,resort_hotel,no,7,2015,july,1,0,1,1,0,0,bb,united_kingdom,direct,direct,no,0,0,a,c,0,no_deposit,0,transient,75.0,0,0,check_out,2015-01-02 00:07:00,2015,January

-----------------------------------------------------------

La información básica del Dataframe es la siguiente:

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_day_of_month       119390 non-null  int64
 6   stays_in_weekend_nights         119390 non-null  int64
 7   stays_in_week_nights            119390 non-null  int64
 8   adults                          119390 non-null  int64
 9   children                        119390 non-null  Int64
 10  babies                          119390 non-null  int64
 11  meal                            119390 non-null  str
 12  country                         119390 non-null  str
 13  market_segment                  119390 non-null  str
 14  distribution_channel            119390 non-null  str
 15  is_repeated_guest               119390 non-null  object
 16  previous_cancellations          119390 non-null  int64
 17  previous_bookings_not_canceled  119390 non-null  int64
 18  reserved_room_type              119390 non-null  str
 19  assigned_room_type              119390 non-null  str
 20  booking_changes                 119390 non-null  int64
 21  deposit_type                    119390 non-null  str
 22  days_in_waiting_list            119390 non-null  int64
 23  customer_type                   119390 non-null  str
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status              119390 non-null  str
 28  reservation_status_date         119390 non-null  datetime64[us]
 29  reservation_status_year         119390 non-null  int32
 30  reservation_status_month        119390 non-null  str
dtypes: Int64(1), datetime64[us](1), float64(1), int32(1), int64(13), object(2), str(12)
memory usage: 27.9+ MB

-----------------------------------------------------------

El número de nulos por columna del Dataframe es:

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
reservation_status_year           0
reservation_status_month          0
dtype: int64

Y los datos de la variable `reservation_status_month` empiezan por mayúsculas, los cambiamos a minúsculas para mantener la consistencia en todo el DataFrame:

In [ ]:
minus(booking_limpio, ['reservation_status_month'])

### **`reviews_limpio`**

In [ ]:
# Llamamos a la función analisis_rapido guardada en el archivo de soporte
analisis_rapido(reviews_limpio)

Las 3 primeras filas del Dataframe son:

,hotel_address,additional_number_of_scoring,review_date,average_score,hotel_name,reviewer_nationality,negative_review,review_total_negative_word_counts,total_number_of_reviews,positive_review,review_total_positive_word_counts,total_number_of_reviews_reviewer_has_given,reviewer_score,tags,days_since_review,lat,lng
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968
2,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/2017,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,7.1,"[' Leisure trip ', ' Family with young childre...",3 days,52.360576,4.915968

-----------------------------------------------------------

La información básica del Dataframe es la siguiente:

<class 'pandas.DataFrame'>
RangeIndex: 515738 entries, 0 to 515737
Data columns (total 17 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   hotel_address                               515738 non-null  str
 1   additional_number_of_scoring                515738 non-null  int64
 2   review_date                                 515738 non-null  str
 3   average_score                               515738 non-null  float64
 4   hotel_name                                  515738 non-null  str
 5   reviewer_nationality                        515738 non-null  str
 6   negative_review                             515738 non-null  str
 7   review_total_negative_word_counts           515738 non-null  int64
 8   total_number_of_reviews                     515738 non-null  int64
 9   positive_review                             515738 non-null  str
 10  review_total_positive_word_counts           515738 non-null  int64
 11  total_number_of_reviews_reviewer_has_given  515738 non-null  int64
 12  reviewer_score                              515738 non-null  float64
 13  tags                                        515738 non-null  str
 14  days_since_review                           515738 non-null  str
 15  lat                                         512470 non-null  float64
 16  lng                                         512470 non-null  float64
dtypes: float64(4), int64(5), str(8)
memory usage: 66.9 MB

-----------------------------------------------------------

El número de nulos por columna del Dataframe es:

hotel_address                                    0
additional_number_of_scoring                     0
review_date                                      0
average_score                                    0
hotel_name                                       0
reviewer_nationality                             0
negative_review                                  0
review_total_negative_word_counts                0
total_number_of_reviews                          0
positive_review                                  0
review_total_positive_word_counts                0
total_number_of_reviews_reviewer_has_given       0
reviewer_score                                   0
tags                                             0
days_since_review                                0
lat                                           3268
lng                                           3268
dtype: int64

Hemos verificado que la limpieza de ambos dataframes se ha realizado correctamente: 

- Los nombres de las columnas son claros y descriptivos.
- Los datos son consistentes entre sí.
- No se observan valores nulos.
- Las variables presentan formatos adecuados para análisis y modelado posteriores .

Además, las transformaciones aplicadas (como estandarización de texto, conversión de tipos numéricos y codificación de variables categóricas) aseguran que ambos dataframes puedan combinarse y utilizarse de manera confiable.

- **Guardamos los dataset limpios**

In [ ]:
booking_limpio.to_csv("../data/output/booking_limpio.csv", index=False)
reviews_limpio.to_csv("../data/output/reviews_limpio.csv", index=False)

---